/**
 * Comprehensive fake data for UI preview — no API calls needed.
 * Every field on every entity is populated so all UI paths are exercised.
 */
import type { SpotOnResults } from "../types/api";

export const FAKE_RESULTS: SpotOnResults = {
  constraints: {
    origin: "New York, US",
    destination: "Tokyo, JP",
    departing_date: "2026-03-15",
    returning_date: "2026-03-20",
  },

  restaurants: [
    {
      id: "r1",
      name: "Sukiyabashi Jiro",
      cuisine: "Sushi / Omakase",
      area: "Ginza, Chuo",
      operating_hours: "Mon–Sat 11:30 AM – 2:00 PM, 5:30 PM – 8:30 PM",
      price_range: "$$$$",
      url: "https://www.sushi-jiro.jp",
      menu_url: "https://www.sushi-jiro.jp/menu",
      reservation_url: "https://www.sushi-jiro.jp/reserve",
      snippet: "World-renowned sushi restaurant featured in the documentary 'Jiro Dreams of Sushi'. Master Jiro Ono serves an exquisite 20-course omakase using the freshest seasonal fish.",
      why_recommended: "A once-in-a-lifetime culinary experience. The 20-course omakase is meticulously crafted by a living legend of Japanese cuisine, using fish sourced from Tsukiji's finest vendors.",
      rating: 4.9,
      tags: ["Michelin 3-Star", "Omakase", "Reservation Required"],
    },
    {
      id: "r2",
      name: "Ichiran Shibuya",
      cuisine: "Ramen",
      area: "Shibuya",
      operating_hours: "Daily 24 Hours",
      price_range: "$$",
      url: "https://en.ichiran.com",
      menu_url: "https://en.ichiran.com/menu",
      reservation_url: null,
      snippet: "Famous tonkotsu ramen chain with solo dining booths and a customizable ordering system. Each bowl is tailored to your exact preference for richness, spice, and noodle firmness.",
      why_recommended: "The ultimate solo ramen experience — customize every aspect of your bowl from a paper form. Perfect for a late-night meal after exploring Shibuya's nightlife.",
      rating: 4.5,
      tags: ["Tonkotsu", "Solo Dining", "Late Night"],
    },
    {
      id: "r3",
      name: "Narisawa",
      cuisine: "Innovative Japanese / French",
      area: "Minato-ku, Aoyama",
      operating_hours: "Tue–Sat 12:00 PM – 1:30 PM, 6:00 PM – 9:00 PM",
      price_range: "$$$$",
      url: "https://www.narisawa-yoshihiro.com",
      menu_url: "https://www.narisawa-yoshihiro.com/menu",
      reservation_url: "https://www.narisawa-yoshihiro.com/reservation",
      snippet: "Chef Yoshihiro Narisawa's restaurant blends French technique with Japanese philosophy. The 'Satoyama' cuisine celebrates the connection between nature and gastronomy.",
      why_recommended: "Ranked among Asia's 50 Best Restaurants. The tasting menu tells a story of Japanese forests and landscapes through innovative dishes that are as beautiful as they are delicious.",
      rating: 4.8,
      tags: ["Michelin 2-Star", "Tasting Menu", "Innovative"],
    },
    {
      id: "r4",
      name: "Tsukiji Sushisay",
      cuisine: "Sushi",
      area: "Tsukiji, Chuo",
      operating_hours: "Mon–Sat 7:00 AM – 2:00 PM",
      price_range: "$$$",
      url: "https://www.sushisay.co.jp",
      menu_url: null,
      reservation_url: "https://www.sushisay.co.jp/book",
      snippet: "Located steps from the old Tsukiji fish market, this family-run sushi bar has been serving the freshest catches since 1952. Known for their generous negitoro and uni.",
      why_recommended: "An authentic market sushi experience without the tourist crowds. The chef's daily selection (omakase) at the counter is exceptional value for the quality.",
      rating: 4.6,
      tags: ["Market Fresh", "Counter Seating", "Heritage"],
    },
  ],

  travel_spots: [
    {
      id: "a1",
      name: "Senso-ji Temple",
      kind: "Historic Temple",
      area: "Asakusa, Taito",
      operating_hours: "Daily 6:00 AM – 5:00 PM (grounds open 24h)",
      url: "https://www.senso-ji.jp",
      reservation_url: null,
      admission_price: "Free",
      snippet: "Tokyo's oldest and most significant Buddhist temple, dating back to 645 AD. The iconic Kaminarimon gate with its massive red lantern is one of Japan's most photographed landmarks.",
      why_recommended: "A must-visit for first-time Tokyo visitors. Walk through the vibrant Nakamise shopping street to reach the main hall, and don't miss the five-story pagoda illuminated at night.",
      estimated_duration_min: 90,
    },
    {
      id: "a2",
      name: "teamLab Borderless",
      kind: "Digital Art Museum",
      area: "Azabudai Hills, Minato",
      operating_hours: "Daily 10:00 AM – 9:00 PM",
      url: "https://www.teamlab.art/e/borderless-azabudai",
      reservation_url: "https://www.teamlab.art/e/borderless-azabudai/tickets",
      admission_price: "¥3,800 (~$25)",
      snippet: "An immersive digital art museum where artworks flow out of rooms, communicate with other works, and merge with visitors. A boundary-less world of 60+ interactive installations.",
      why_recommended: "One of the most unique art experiences in the world. The installations respond to your movement and touch — every visit is different. Book tickets in advance as it sells out quickly.",
      estimated_duration_min: 150,
    },
    {
      id: "a3",
      name: "Meiji Jingu Shrine",
      kind: "Shinto Shrine",
      area: "Shibuya, Harajuku",
      operating_hours: "Daily Sunrise – Sunset",
      url: "https://www.meijijingu.or.jp/en",
      reservation_url: null,
      admission_price: "Free (¥500 for inner garden)",
      snippet: "Dedicated to Emperor Meiji, this tranquil shrine sits in a 170-acre forest of 120,000 trees in the heart of Tokyo. A peaceful escape from the city's energy.",
      why_recommended: "The juxtaposition of this serene forested shrine against nearby Harajuku's pop-culture madness is quintessentially Tokyo. Visit early morning to see traditional wedding processions.",
      estimated_duration_min: 60,
    },
  ],

  hotels: [
    {
      id: "h1",
      name: "Aman Tokyo",
      area: "Otemachi, Chiyoda",
      price_per_night: "$980",
      url: "https://www.aman.com/hotels/aman-tokyo",
      snippet: "Occupying the top six floors of the Otemachi Tower, Aman Tokyo offers panoramic views of the Imperial Palace gardens and Mount Fuji. Traditional Japanese aesthetics meet modern luxury.",
      why_recommended: "The ultimate luxury stay in Tokyo. Floor-to-ceiling windows frame stunning city views, while the 2,500 sqm spa features a traditional Japanese onsen. Impeccable, understated service.",
      amenities: ["Spa & Onsen", "Pool", "Fine Dining", "Imperial Palace Views", "Concierge"],
    },
    {
      id: "h2",
      name: "Park Hyatt Tokyo",
      area: "Nishi-Shinjuku, Shinjuku",
      price_per_night: "$520",
      url: "https://www.hyatt.com/en-US/hotel/japan/park-hyatt-tokyo",
      snippet: "Made famous by 'Lost in Translation', this iconic hotel occupies the top 14 floors of the Shinjuku Park Tower with breathtaking views of Mount Fuji and the Shinjuku skyline.",
      why_recommended: "The New York Bar on the 52nd floor with live jazz and city views is worth the stay alone. Rooms are spacious by Tokyo standards with deep soaking tubs and floor-to-ceiling windows.",
      amenities: ["New York Bar", "Pool", "Gym", "Spa", "Club Lounge"],
    },
    {
      id: "h3",
      name: "MUJI Hotel Ginza",
      area: "Ginza, Chuo",
      price_per_night: "$210",
      url: "https://hotel.muji.com/ginza/en",
      snippet: "A minimalist boutique hotel by the beloved Japanese brand, located above the world's largest MUJI store. Rooms embody the brand's philosophy of simplicity and natural materials.",
      why_recommended: "Perfect for design lovers on a reasonable budget. The rooms use reclaimed wood, stone, and organic cotton. Central Ginza location makes it an ideal base for exploring Tokyo.",
      amenities: ["MUJI Store", "Restaurant", "Lounge", "Central Location"],
    },
  ],

  car_rentals: [
    {
      id: "c1",
      provider: "Times Car Rental",
      vehicle_class: "Compact (Toyota Aqua Hybrid)",
      price_per_day: "¥5,500 (~$37)",
      pickup_location: "Narita Airport Terminal 1",
      operating_hours: "Daily 7:00 AM – 10:00 PM",
      url: "https://rental.timescar.jp/en",
      why_recommended: "Best value for airport pickup. The Toyota Aqua gets excellent fuel economy for day trips to Mt. Fuji or Hakone. English GPS included at no extra charge.",
    },
    {
      id: "c2",
      provider: "Nippon Rent-A-Car",
      vehicle_class: "Standard (Nissan Note e-POWER)",
      price_per_day: "¥7,200 (~$48)",
      pickup_location: "Tokyo Station Marunouchi",
      operating_hours: "Daily 8:00 AM – 8:00 PM",
      url: "https://www.nipponrentacar.co.jp/en",
      why_recommended: "Most convenient city pickup location right at Tokyo Station. The Nissan Note e-POWER is a hybrid with excellent city fuel economy and a surprisingly roomy interior.",
    },
    {
      id: "c3",
      provider: "Toyota Rent a Car",
      vehicle_class: "SUV (Toyota RAV4)",
      price_per_day: "¥12,000 (~$80)",
      pickup_location: "Haneda Airport Terminal 3",
      operating_hours: "Daily 6:00 AM – 11:00 PM",
      url: "https://rent.toyota.co.jp/en",
      why_recommended: "Best option if you plan to explore the Japanese countryside. The RAV4 handles mountain roads well and has ample luggage space for extended trips outside Tokyo.",
    },
  ],

  flights: [
    {
      id: "f1",
      airline: "ANA (All Nippon Airways)",
      route: "JFK → NRT (New York → Tokyo Narita)",
      trip_type: "round-trip",
      price_range: "$1,200 – $1,600",
      url: "https://www.ana.co.jp/en/us",
      snippet: "Direct flight, 14h 10m outbound. ANA's flagship service with lie-flat seats in business class and award-winning Japanese hospitality.",
      why_recommended: "Japan's 5-star airline with the most comfortable economy seats on the JFK-NRT route. Direct flights save 4+ hours compared to connections. In-flight Japanese cuisine is exceptional.",
    },
    {
      id: "f2",
      airline: "Japan Airlines (JAL)",
      route: "JFK → HND (New York → Tokyo Haneda)",
      trip_type: "round-trip",
      price_range: "$1,350 – $1,800",
      url: "https://www.jal.co.jp/en",
      snippet: "Direct flight, 14h 30m outbound. JAL's Sky Suite offers one of the best business class products globally. Haneda is closer to central Tokyo than Narita.",
      why_recommended: "Haneda Airport is only 20 minutes from central Tokyo by monorail, saving you significant transfer time compared to Narita. JAL's service is consistently top-tier.",
    },
    {
      id: "f3",
      airline: "Delta Air Lines",
      route: "JFK → NRT (New York → Tokyo Narita)",
      trip_type: "one-way",
      price_range: "$580 – $850",
      url: "https://www.delta.com",
      snippet: "Direct flight, 14h 15m. Delta One suites available with sliding doors for privacy. SkyMiles members earn elevated miles on transpacific routes.",
      why_recommended: "Most affordable direct option from JFK. If you're a SkyMiles member, this route earns significant miles. Delta One suites rival Japanese carrier business class at a lower price.",
    },
  ],

  references: [
    // Restaurants
    { title: "Tokyo's Best Sushi: A 2026 Guide", url: "https://www.timeout.com/tokyo/restaurants/best-sushi-in-tokyo", content: "An updated guide to the best sushi restaurants in Tokyo, from high-end omakase to affordable conveyor belt options.", section: "restaurant" },
    { title: "Where to Eat Ramen in Tokyo", url: "https://www.eater.com/maps/best-ramen-tokyo", content: "A neighborhood-by-neighborhood guide to Tokyo's best ramen shops, from classic tonkotsu to innovative miso varieties.", section: "restaurant" },
    { title: "Asia's 50 Best Restaurants 2026", url: "https://www.theworlds50best.com/asia/en/list/1-50", content: "The definitive annual ranking of Asia's finest dining establishments, featuring multiple Tokyo restaurants in the top 20.", section: "restaurant" },
    // Hotels
    { title: "Best Luxury Hotels in Tokyo", url: "https://www.cntraveler.com/gallery/best-hotels-in-tokyo", content: "Condé Nast Traveler's curated selection of Tokyo's finest hotels, from traditional ryokans to contemporary design hotels.", section: "hotel" },
    { title: "Where to Stay in Tokyo: Neighborhood Guide", url: "https://www.nomadicmatt.com/travel-blogs/where-to-stay-in-tokyo", content: "A comprehensive breakdown of Tokyo's best neighborhoods for tourists, with hotel recommendations for every budget.", section: "hotel" },
    // Attractions
    { title: "Top 20 Things to Do in Tokyo in 2026", url: "https://www.lonelyplanet.com/japan/tokyo/top-things-to-do", content: "Lonely Planet's essential guide to Tokyo's must-see attractions, from ancient temples to cutting-edge art museums.", section: "attraction" },
    { title: "teamLab Borderless: Complete Visitor Guide", url: "https://www.japanguide.com/e/e3064.html", content: "Everything you need to know before visiting teamLab Borderless, including ticket booking tips and best times to visit.", section: "attraction" },
    // Cars
    { title: "Renting a Car in Japan: Complete Guide", url: "https://www.japan-guide.com/e/e2024.html", content: "A practical guide covering international driving permits, toll roads, and the best car rental companies in Japan.", section: "car" },
    // Flights
    { title: "Best Airlines for Flying to Japan", url: "https://thepointsguy.com/guide/best-airlines-to-japan", content: "A comparison of direct flight options from US cities to Tokyo, including comfort, price, and loyalty program perks.", section: "flight" },
    { title: "Narita vs Haneda: Which Tokyo Airport?", url: "https://www.japan-guide.com/e/e2027.html", content: "A detailed comparison of Tokyo's two major airports, including transfer times, costs, and airline availability.", section: "flight" },
  ],

  report: {
    total_estimated_budget: "$2,768",
  },
};
